#Postgresql Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://dpg-daejk1id0e5s738p7rug-a.singapore-postgres.render.com:5432/moneymanger_evt6?sslmode=require}
spring.datasource.username=${DATABASE_USERNAME:moneymanger_evt6_user}
spring.datasource.password=${DATABASE_PASSWORD}

# Render configuration
server.port=${PORT:8080}

# Email configuration
spring.mail.host=${BREVO_HOST:smtp-relay.brevo.com}
spring.mail.port=${BREVO_PORT:587}
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${BREVO_FROM_EMAIL}

# Application URLs and JWT
jwt.secret=${JWT_SECRET}
money.manager.frontend.url=${MONEY_MANAGER_FRONTEND_URL}
app.activation.url=${MONEY_MANAGER_BACKEND_URL}
