#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-daejk1id0e5s738p7rug-a.singapore-postgres.render.com/moneymanger_evt6
spring.datasource.username=moneymanger_evt6_user
spring.datasource.password=KdvQxk145kAQo8IQXX4ciqjwhuGMMnWy
